credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: hashed_password_for_abc
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: hashed_password_for_def
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com